export const SET_EDIT_MESSAGE = 'MESSAGE_ACTION:SET_EDIT_MESSAGE';
export const SET_MESSAGES = 'MESSAGE_ACTION:SET_MESSAGES';
export const ADD_MESSAGE = 'MESSAGE_ACTION:ADD_MESSAGE';
export const EDIT_MESSAGE = 'MESSAGE_ACTION:EDIT_MESSAGE';
export const REMOVE_MESSAGE = 'MESSAGE_ACTION:REMOVE_MESSAGE';
export const SET_LAST_MESSAGE_DATE = 'MESSAGE_ACTION:SET_LAST_MESSAGE_DATE';
